### ISSUE TITLE
DENO_DIR is not set

### ISSUE THREAD

**Issue by aaronwlee** [denofn/denopack#1]
error: Uncaught Error: DENO_DIR is not set
if (!deno_dir) throw new Error(`DENO_DIR is not set`);
                     ^
    at mod.ts:2:22

as far as I know, DENO_DIR env is not exist

**Comment by jeroenptrs** [comment]
Hey @aaronwlee what OS are you on? Windows?

**Comment by jeroenptrs** [comment]
```
Deno caches remote imports in a special directory specified by the DENO_DIR environment variable. It defaults to the system's cache directory if DENO_DIR is not specified. The next time you run the program, no downloads will be made. If the program hasn't changed, it won't be recompiled either. The default directory is:

On Linux/Redox: $XDG_CACHE_HOME/deno or $HOME/.cache/deno
On Windows: %LOCALAPPDATA%/deno (%LOCALAPPDATA% = FOLDERID_LocalAppData)
On macOS: $HOME/Library/Caches/deno
If something fails, it falls back to $HOME/.deno
```

I'll add fallbacks to these folders and an option to pass a custom path to the Deno root folder in the next release.

This would only occur if you're using `pluginCacheResolver` or one of the hooks that uses it internally.
You _could_ use the `useCompile` hook in the meantime, which also automatically uses the correct cache folder.

**Comment by aaronwlee** [comment]
I've tested it in Windows 10 2004 (19041.388 build) and WSL (Ubuntu bionic)

you can get some hint from here I think :)

https://github.com/timreichen/Bundler/blob/master/cache.ts

**Comment by jeroenptrs** [comment]
@aaronwlee I just published a new version with better cach support. Can you check if this behaviour has changed with denopack 0.2.0?

**Comment by jeroenptrs** [comment]
I spun up a remote Linux server to check if it now resolves properly, so I'm closing this issue for now.
@aaronwlee if issues on Windows persist feel free to reopen this issue 🙂
