### ISSUE TITLE
Remote debugging in VS Code

### ISSUE THREAD

**Issue by alex0ne** [denofn/denopack#27]
Remote debugging in VS Code and Google Chrome not working properly after denopack bundling.

Operating system: MacOS Catalina 10.15.6
Deno version: 1.3.3
VS Code version: 1.49.0

Steps to reproduce the issue:

- Open [react-template](https://github.com/denofn/denopack/tree/main/recipes/react-template) in VS Code.

- Create "dist" folder in the root directory.

- Run `denopack -c denopack.config.ts` to bundle the project and serve files from the dist directory on port 3000.

- Open Google Chrome with remote debugging enabled with this command: 
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --user-data-dir=/tmp/chrome-debug`

- Open http://localhost:9222/json to verify if Chrome is running with remote debugging enabled on port 9222.

- Add this configuration to launch.json file in .vscode folder:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Chrome",
            "port": 9222,
            "request": "attach",
            "type": "pwa-chrome",
            "webRoot": "${workspaceFolder}"
        },
    ]
}
```

- Attach some breakpoints to src/App.tsx
- Open [localhost:3000](localhost:3000).
- Run debugger with "Attach to Chrome" configuration.

Result: All breakpoints are unbounded and inaccessible from the debugger.

Can you please, give me some guidance, how to setup and use remote debugging with VSCode, Chrome, and Denopack?

The same configuration is working fine with the create-react-app typescript template.

**Comment by jeroenptrs** [comment]
Terser strips debugger statements by default, that's my guess as to what's causing this.
https://terser.org/docs/api-reference.html#compress-options `drop_debugger`.

If it still persists feel free to reopen this issue!

Additionally, @alex0ne can you please use the bug report issue template for future issues?
