### ISSUE TITLE
TS error in rollup dependency on package install/run

### ISSUE THREAD

**Issue by shinobi5** [denofn/denopack#7]
I was actually thinking of building a bundler for Deno because its internal bundler isn't great for client-side output...

On that note I tried to install this package globally while also trying to just run the CLI via velociraptor. But I get this error:
```
error: TS1031 at https://unpkg.com/rollup@2.23.0/dist/es/rollup.browser.js:11:39947,Unexpected token Some(LParen) at https://unpkg.com/rollup@2.23.0/dist/es/rollup.browser.js:11:39954
```
Are you aware of this?

**Comment by jeroenptrs** [comment]
@shinobi5 can you share exactly what you're doing and what OS you are on?

**Comment by jeroenptrs** [comment]
I just ran `deno cache https://unpkg.com/rollup@2.23.0/dist/es/rollup.browser.js --reload` and see no issues thus far.
Waiting for further input from @shinobi5

**Comment by shinobi5** [comment]
Here's my velociraptor  script:

```
bundle: deno run --unstable --allow-read --allow-write https://deno.land/x/denopack@0.4.0/cli.ts -i src/index.ts -o src/index.js
```

Then run `vr bundle`.

Deno starts downloading the dependencies and then the error occurs...

This also happens when running the global install script:

```
deno install --unstable --allow-read --allow-write --allow-env --allow-net -n denopack https://deno.land/x/denopack@0.4.0/cli.ts
```

I'm on Manjaro/KDE linux.

**Comment by shinobi5** [comment]
![image](https://user-images.githubusercontent.com/7435552/89875585-8dd01300-dc11-11ea-8dc7-891542a0c1d7.png)

**Comment by jeroenptrs** [comment]
@shinobi5 what version of deno are you running?

**Comment by shinobi5** [comment]
Hmm `1.0.3`. I'll upgrade and see what happens.

**Comment by jeroenptrs** [comment]
@shinobi5 I just rolled back to 1.0.3 and the issue appears there. Upgrading to the latest version should resolve the issue. I'll add minimum version requirements to the readme. Big thanks!

**Comment by jeroenptrs** [comment]
From further investigating it appears that the minimum required Deno version is 1.2.0
Updating this in the bug template and readme. Closing for now. If anything else related pops up let me know @shinobi5 !
